/**
 * AutoCoder - Deterministic Code Generation Service
 *
 * Generates boilerplate code using template-based algorithms instead of LLM calls.
 * This reduces token usage by 100% for common patterns that can be deterministically generated.
 *
 * Supported patterns:
 * - CRUD operations
 * - REST API endpoints
 * - React components
 * - TypeScript types/interfaces
 * - Database schemas
 * - Test files
 * - Configuration files
 */
import { logger } from "../lib/logger";

export type CodePattern =
  | "crud-api"
  | "react-component"
  | "typescript-interface"
  | "database-schema"
  | "test-file"
  | "config-file"
  | "hook"
  | "service"
  | "model"
  | "middleware";

export interface AutocoderInput {
  pattern: CodePattern;
  name: string;
  options?: {
    language?: string;
    framework?: string;
    database?: string;
    addTypes?: boolean;
    addTests?: boolean;
    addDocs?: boolean;
  };
}

export interface AutocoderResult {
  success: boolean;
  files: Array<{ path: string; content: string }>;
  tokenSavings: number;
  pattern: CodePattern;
  message?: string;
}

interface TemplateGenerator {
  generate(input: AutocoderInput): string;
  supportsLanguage(lang: string): boolean;
}

// ─── TypeScript Interface Generator ────────────────────────────────────────────

const typeScriptInterfaceGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "tsx"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const pascalName = toPascalCase(name);
    const typeName = options?.addTypes ? `${pascalName}Type` : pascalName;

    let fields = "";
    switch (options?.framework) {
      case "react":
        fields = `  id: string;
  createdAt: Date;
  updatedAt: Date;`;
        break;
      case "api":
        fields = `  id: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;`;
        break;
      default:
        fields = `  id: string;
  name: string;
  value: unknown;`;
    }

    let interfaceCode = `export interface ${typeName} {\n${fields}\n}\n`;

    if (options?.addTypes) {
      interfaceCode += `\nexport type ${pascalName}Input = Partial<Omit<${typeName}, "id" | "createdAt" | "updatedAt">>>;\n`;
      interfaceCode += `export type ${pascalName}Output = ${typeName};\n`;
    }

    if (options?.addDocs) {
      interfaceCode = `/**\n * ${pascalName} interface\n * Generated by AutoCoder\n */\n\n` + interfaceCode;
    }

    return interfaceCode;
  },
};

// ─── React Component Generator ────────────────────────────────────────────────

const reactComponentGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "tsx"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const pascalName = toPascalCase(name);
    const isHook = options?.framework === "hook";

    let code = "";

    if (options?.addDocs) {
      code += `/**\n * ${pascalName} ${isHook ? "hook" : "component"}\n * Generated by AutoCoder\n */\n\n`;
    }

    if (isHook) {
      code += `import { useState, useEffect, useCallback } from 'react';\n\n`;
      code += `export function use${pascalName}() {\n`;
      code += `  const [data, setData] = useState<unknown>(null);\n`;
      code += `  const [loading, setLoading] = useState(false);\n`;
      code += `  const [error, setError] = useState<Error | null>(null);\n\n`;
      code += `  const fetchData = useCallback(async () => {\n`;
      code += `    setLoading(true);\n`;
      code += `    try {\n`;
      code += `      // TODO: Implement fetch logic\n`;
      code += `      setData(null);\n`;
      code += `    } catch (e) {\n`;
      code += `      setError(e as Error);\n`;
      code += `    } finally {\n`;
      code += `      setLoading(false);\n`;
      code += `    }\n`;
      code += `  }, []);\n\n`;
      code += `  useEffect(() => {\n`;
      code += `    fetchData();\n`;
      code += `  }, [fetchData]);\n\n`;
      code += `  return { data, loading, error, refetch: fetchData };\n`;
      code += `}\n`;
    } else {
      code += `import React from 'react';\n\n`;
      code += `interface ${pascalName}Props {\n`;
      code += `  className?: string;\n`;
      code += `}\n\n`;
      code += `export function ${pascalName}({ className }: ${pascalName}Props) {\n`;
      code += `  return (\n`;
      code += `    <div className={className}>\n`;
      code += `      {/* TODO: Implement ${pascalName} */}\n`;
      code += `    </div>\n`;
      code += `  );\n`;
      code += `}\n`;
    }

    return code;
  },
};

// ─── CRUD API Generator ────────────────────────────────────────────────────────

const crudApiGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "javascript", "js"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const pascalName = toPascalCase(name);
    const camelName = toCamelCase(name);

    const isExpress = options?.framework === "express";
    const isNextApi = options?.framework === "nextjs";

    let code = "";

    if (options?.addDocs) {
      code += `/**\n * ${pascalName} CRUD API\n * Generated by AutoCoder\n */\n\n`;
    }

    if (isExpress) {
      code += `import { Router, Request, Response } from 'express';\n`;
      code += `const router = Router();\n\n`;
      code += `// GET all ${camelName}s\n`;
      code += `router.get('/', async (req: Request, res: Response) => {\n`;
      code += `  try {\n`;
      code += `    // TODO: Implement fetching all ${camelName}s\n`;
      code += `    res.json({ data: [] });\n`;
      code += `  } catch (error) {\n`;
      code += `    res.status(500).json({ error: 'Failed to fetch ${camelName}s' });\n`;
      code += `  }\n});\n\n`;
      code += `// GET single ${camelName}\n`;
      code += `router.get('/:id', async (req: Request, res: Response) => {\n`;
      code += `  try {\n`;
      code += `    const { id } = req.params;\n`;
      code += `    // TODO: Implement fetching ${camelName} by id\n`;
      code += `    res.json({ data: null });\n`;
      code += `  } catch (error) {\n`;
      code += `    res.status(500).json({ error: 'Failed to fetch ${camelName}' });\n`;
      code += `  }\n});\n\n`;
      code += `// POST create ${camelName}\n`;
      code += `router.post('/', async (req: Request, res: Response) => {\n`;
      code += `  try {\n`;
      code += `    // TODO: Implement creating ${camelName}\n`;
      code += `    res.status(201).json({ data: {} });\n`;
      code += `  } catch (error) {\n`;
      code += `    res.status(500).json({ error: 'Failed to create ${camelName}' });\n`;
      code += `  }\n});\n\n`;
      code += `// PUT update ${camelName}\n`;
      code += `router.put('/:id', async (req: Request, res: Response) => {\n`;
      code += `  try {\n`;
      code += `    const { id } = req.params;\n`;
      code += `    // TODO: Implement updating ${camelName}\n`;
      code += `    res.json({ data: {} });\n`;
      code += `  } catch (error) {\n`;
      code += `    res.status(500).json({ error: 'Failed to update ${camelName}' });\n`;
      code += `  }\n});\n\n`;
      code += `// DELETE ${camelName}\n`;
      code += `router.delete('/:id', async (req: Request, res: Response) => {\n`;
      code += `  try {\n`;
      code += `    const { id } = req.params;\n`;
      code += `    // TODO: Implement deleting ${camelName}\n`;
      code += `    res.status(204).send();\n`;
      code += `  } catch (error) {\n`;
      code += `    res.status(500).json({ error: 'Failed to delete ${camelName}' });\n`;
      code += `  }\n});\n\n`;
      code += `export default router;\n`;
    } else if (isNextApi) {
      code += `import { NextResponse } from 'next/server';\n\n`;
      code += `// GET /api/${camelName}\nexport async function GET() {\n`;
      code += `  // TODO: Implement fetching all ${camelName}s\n`;
      code += `  return NextResponse.json({ data: [] });\n}\n\n`;
      code += `// POST /api/${camelName}\nexport async function POST(request: Request) {\n`;
      code += `  const body = await request.json();\n`;
      code += `  // TODO: Implement creating ${camelName}\n`;
      code += `  return NextResponse.json({ data: {} }, { status: 201 });\n}\n`;
    } else {
      code += `// ${pascalName} Service\n`;
      code += `export class ${pascalName}Service {\n`;
      code += `  async findAll() {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return [];\n`;
      code += `  }\n\n`;
      code += `  async findById(id: string) {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return null;\n`;
      code += `  }\n\n`;
      code += `  async create(data: Partial<unknown>) {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return {};\n`;
      code += `  }\n\n`;
      code += `  async update(id: string, data: Partial<unknown>) {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return {};\n`;
      code += `  }\n\n`;
      code += `  async delete(id: string) {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return true;\n`;
      code += `  }\n`;
      code += `}\n`;
    }

    return code;
  },
};

// ─── Test File Generator ────────────────────────────────────────────────────────

const testFileGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "javascript", "js"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const pascalName = toPascalCase(name);
    const isVitest = options?.framework === "vitest";

    let code = "";
    const importPath = options?.framework === "react" ? `../components/${pascalName}` : `../services/${pascalName}`;

    if (isVitest) {
      code += `import { describe, it, expect, vi } from 'vitest';\n`;
      code += `import { render, screen } from '@testing-library/react';\n`;
    } else {
      code += `import { describe, it, expect, jest } from '@jest/globals';\n`;
    }

    code += `import { ${pascalName} } from '${importPath}';\n\n`;

    code += `describe('${pascalName}', () => {\n`;
    code += `  it('should render without crashing', () => {\n`;
    if (options?.framework === "react") {
      code += `    expect(() => render(<${pascalName} />)).not.toThrow();\n`;
    } else {
      code += `    expect(${pascalName}).toBeDefined();\n`;
    }
    code += `  });\n\n`;

    code += `  it('should have correct structure', () => {\n`;
    code += `    // TODO: Add specific tests\n`;
    code += `    expect(true).toBe(true);\n`;
    code += `  });\n`;
    code += `});\n`;

    return code;
  },
};

// ─── Database Schema Generator ──────────────────────────────────────────────────

const databaseSchemaGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["sql", "typescript", "ts"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const tableName = toSnakeCase(name);
    const dbType = options?.database || "postgresql";

    let code = "";

    if (options?.addDocs) {
      code += `-- ${toPascalCase(name)} table\n`;
      code += `-- Generated by AutoCoder\n\n`;
    }

    if (dbType === "postgresql" || dbType === "supabase") {
      code += `CREATE TABLE ${tableName} (\n`;
      code += `  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n`;
      code += `  name VARCHAR(255) NOT NULL,\n`;
      code += `  description TEXT,\n`;
      code += `  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n`;
      code += `  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n`;
      code += `);\n\n`;
      code += `-- Enable Row Level Security\n`;
      code += `ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;\n\n`;
      code += `-- Create indexes\n`;
      code += `CREATE INDEX idx_${tableName}_created_at ON ${tableName}(created_at);\n`;
    } else if (dbType === "mysql") {
      code += `CREATE TABLE ${tableName} (\n`;
      code += `  id VARCHAR(36) PRIMARY KEY,\n`;
      code += `  name VARCHAR(255) NOT NULL,\n`;
      code += `  description TEXT,\n`;
      code += `  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n`;
      code += `  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP\n`;
      code += `);\n\n`;
      code += `CREATE INDEX idx_${tableName}_created_at ON ${tableName}(created_at);\n`;
    } else {
      code += `// Prisma schema for ${toPascalCase(name)}\n`;
      code += `model ${toPascalCase(name)} {\n`;
      code += `  id        String   @id @default(uuid())\n`;
      code += `  name      String\n`;
      code += `  description String?\n`;
      code += `  createdAt DateTime @default(now())\n`;
      code += `  updatedAt DateTime @updatedAt\n`;
      code += `}\n`;
    }

    return code;
  },
};

// ─── Config File Generator ─────────────────────────────────────────────────────

const configFileGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["json", "yaml", "yml", "typescript", "ts"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const lang = options?.language || "json";

    let code = "";

    if (lang === "json" || lang === "typescript") {
      code = `{
  "name": "${name}",
  "version": "1.0.0",
  "description": "Generated by AutoCoder",
  "main": "src/index.ts",
  "scripts": {
    "dev": "ts-node src/index.ts",
    "build": "tsc",
    "test": "jest"
  },
  "dependencies": {},
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}`;
    } else if (lang === "yaml" || lang === "yml") {
      code = `name: ${name}
version: 1.0.0
description: Generated by AutoCoder

scripts:
  dev: ts-node src/index.ts
  build: tsc
  test: jest

dependencies: {}
devDependencies:
  "@types/node": "^20.0.0
  typescript: ^5.0.0`;
    }

    return code;
  },
};

// ─── Middleware Generator ─────────────────────────────────────────────────────

const middlewareGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "javascript", "js"].includes(lang),

  generate(input): string {
    const { name } = input;
    const pascalName = toPascalCase(name);

    let code = "";

    code += `import { Request, Response, NextFunction } from 'express';\n\n`;
    code += `export function ${pascalName}Middleware(\n`;
    code += `  req: Request,\n`;
    code += `  res: Response,\n`;
    code += `  next: NextFunction\n`;
    code += `) {\n`;
    code += `  try {\n`;
    code += `    // TODO: Implement middleware logic\n`;
    code += `    const canProceed = true;\n\n`;
    code += `    if (!canProceed) {\n`;
    code += `      return res.status(403).json({ error: 'Access denied' });\n`;
    code += `    }\n\n`;
    code += `    next();\n`;
    code += `  } catch (error) {\n`;
    code += `    next(error);\n`;
    code += `  }\n`;
    code += `}\n`;

    return code;
  },
};

// ─── Service Generator ────────────────────────────────────────────────────────

const serviceGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "javascript", "js"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const pascalName = toPascalCase(name);
    const isCrud = options?.framework === "crud";

    let code = "";

    if (options?.addDocs) {
      code += `/**\n * ${pascalName} Service\n * Generated by AutoCoder\n */\n\n`;
    }

    code += `export class ${pascalName}Service {\n`;

    if (isCrud) {
      code += `  private static instance: ${pascalName}Service;\n\n`;
      code += `  private constructor() {}\n\n`;
      code += `  static getInstance(): ${pascalName}Service {\n`;
      code += `    if (!${pascalName}Service.instance) {\n`;
      code += `      ${pascalName}Service.instance = new ${pascalName}Service();\n`;
      code += `    }\n`;
      code += `    return ${pascalName}Service.instance;\n`;
      code += `  }\n\n`;
      code += `  async findAll(): Promise<unknown[]> {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return [];\n`;
      code += `  }\n\n`;
      code += `  async findById(id: string): Promise<unknown | null> {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return null;\n`;
      code += `  }\n\n`;
      code += `  async create(data: unknown): Promise<unknown> {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return data;\n`;
      code += `  }\n\n`;
      code += `  async update(id: string, data: unknown): Promise<unknown | null> {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return null;\n`;
      code += `  }\n\n`;
      code += `  async delete(id: string): Promise<boolean> {\n`;
      code += `    // TODO: Implement\n`;
      code += `    return true;\n`;
      code += `  }\n`;
    } else {
      code += `  async execute(action: string, payload?: unknown): Promise<unknown> {\n`;
      code += `    switch (action) {\n`;
      code += `      default:\n`;
      code += `        throw new Error('Unknown action: ' + action);\n`;
      code += `    }\n`;
      code += `  }\n`;
    }

    code += `}\n`;

    return code;
  },
};

// ─── Model Generator ───────────────────────────────────────────────────────────

const modelGenerator: TemplateGenerator = {
  supportsLanguage: (lang) => ["typescript", "ts", "python", "py"].includes(lang),

  generate(input): string {
    const { name, options } = input;
    const pascalName = toPascalCase(name);

    if (options?.language === "python" || options?.language === "py") {
      return `from dataclasses import dataclass
from datetime import datetime
from typing import Optional

@dataclass
class ${pascalName}:
    """${pascalName} model - Generated by AutoCoder"""
    id: str
    name: str
    created_at: datetime = datetime.now()
    updated_at: datetime = datetime.now()
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }
`;
    }

    return `export class ${pascalName} {
  id: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<${pascalName}> = {}) {
    this.id = data.id || crypto.randomUUID();
    this.name = data.name || '';
    this.createdAt = data.createdAt || new Date();
    this.updatedAt = data.updatedAt || new Date();
  }

  toJSON() {
    return {
      id: this.id,
      name: this.name,
      createdAt: this.createdAt.toISOString(),
      updatedAt: this.updatedAt.toISOString(),
    };
  }

  static fromJSON(json: Record<string, unknown>): ${pascalName} {
    return new ${pascalName}({
      id: json.id as string,
      name: json.name as string,
      createdAt: new Date(json.createdAt as string),
      updatedAt: new Date(json.updatedAt as string),
    });
  }
}
`;
  },
};

// ─── Generator Registry ────────────────────────────────────────────────────────

const GENERATORS: Record<CodePattern, TemplateGenerator> = {
  "crud-api": crudApiGenerator,
  "react-component": reactComponentGenerator,
  "typescript-interface": typeScriptInterfaceGenerator,
  "database-schema": databaseSchemaGenerator,
  "test-file": testFileGenerator,
  "config-file": configFileGenerator,
  "hook": reactComponentGenerator,
  "service": serviceGenerator,
  "model": modelGenerator,
  "middleware": middlewareGenerator,
};

// ─── Helper Functions ────────────────────────────────────────────────────────────

function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
    .replace(/^(.)/, (c) => c.toUpperCase());
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "")
    .replace(/[-_\s]+/g, "_");
}

// ─── Main API ─────────────────────────────────────────────────────────────────

export function generateCode(input: AutocoderInput): AutocoderResult {
  const { pattern, name, options } = input;
  const generator = GENERATORS[pattern];

  if (!generator) {
    return {
      success: false,
      files: [],
      tokenSavings: 0,
      pattern,
      message: `Unknown pattern: ${pattern}`,
    };
  }

  try {
    const content = generator.generate(input);
    const tokenEstimate = Math.ceil(content.length / 4);

    logger.info("AutoCoder", `Generated ${pattern} for "${name}" - saved ~${tokenEstimate} tokens`);

    return {
      success: true,
      files: [
        {
          path: getDefaultFilePath(pattern, name, options),
          content,
        },
      ],
      tokenSavings: tokenEstimate,
      pattern,
      message: `Generated ${pattern} code`,
    };
  } catch (error) {
    logger.error("AutoCoder", `Failed to generate ${pattern}: ${error}`);
    return {
      success: false,
      files: [],
      tokenSavings: 0,
      pattern,
      message: `Generation failed: ${error}`,
    };
  }
}

function getDefaultFilePath(pattern: CodePattern, name: string, options?: AutocoderInput["options"]): string {
  const baseName = toPascalCase(name);
  switch (pattern) {
    case "crud-api":
      return options?.framework === "express" ? `src/routes/${toCamelCase(name)}.ts` : `src/services/${baseName}Service.ts`;
    case "react-component":
      return `src/components/${baseName}/${baseName}.tsx`;
    case "typescript-interface":
      return `src/types/${baseName}.ts`;
    case "database-schema":
      return `database/schema.sql`;
    case "test-file":
      return `tests/${baseName}.test.ts`;
    case "config-file":
      return options?.language === "yaml" ? "config.yaml" : "config.json";
    case "hook":
      return `src/hooks/use${baseName}.ts`;
    case "service":
      return `src/services/${baseName}Service.ts`;
    case "model":
      return `src/models/${baseName}.ts`;
    case "middleware":
      return `src/middleware/${toCamelCase(name)}.ts`;
    default:
      return `src/${name}.ts`;
  }
}

export function canGeneratePattern(pattern: CodePattern): boolean {
  return pattern in GENERATORS;
}

export function getSupportedPatterns(): CodePattern[] {
  return Object.keys(GENERATORS) as CodePattern[];
}

export function estimateTokenSavings(pattern: CodePattern): number {
  const estimates: Record<CodePattern, number> = {
    "crud-api": 150,
    "react-component": 80,
    "typescript-interface": 40,
    "database-schema": 60,
    "test-file": 100,
    "config-file": 30,
    "hook": 120,
    "service": 90,
    "model": 70,
    "middleware": 85,
  };
  return estimates[pattern] || 50;
}
