import diff from 'microdiff';

type DiffResult = ReturnType<typeof diff>[number];

export interface FileChange {
  path: string;
  oldContent: string;
  newContent: string;
  changes: DiffResult[];
}

export interface PlanStep {
  id: string;
  description: string;
  files: FileChange[];
  order: number;
}

export interface MultiFilePlan {
  id: string;
  title: string;
  description: string;
  steps: PlanStep[];
  createdAt: number;
}

// Karpathy-style: Build up code piece by piece
export function createProgressionPlan(
  baseFiles: Record<string, string>,
  targetDescription: string
): MultiFilePlan {
  const steps: PlanStep[] = [];

  // Step 1: Analyze (add comments/structure)
  const step1Files: FileChange[] = Object.entries(baseFiles).map(([path, content]) => {
    const newContent = `// ${targetDescription}\n// Generated by Nexus AI\n\n${content}`;
    return {
      path,
      oldContent: content,
      newContent,
      changes: diff(content.split('\n'), newContent.split('\n')),
    };
  });

  steps.push({
    id: 'step-1-analyze',
    description: 'Add structure and comments',
    files: step1Files,
    order: 1,
  });

  // Step 2: Add imports/core structure
  const step2Files: FileChange[] = step1Files.map(fc => {
    const newContent = fc.newContent + '\n\n// Core implementation\n';
    return {
      path: fc.path,
      oldContent: fc.newContent,
      newContent,
      changes: diff(fc.newContent.split('\n'), newContent.split('\n')),
    };
  });

  steps.push({
    id: 'step-2-structure',
    description: 'Add core structure',
    files: step2Files,
    order: 2,
  });

  return {
    id: `plan-${Date.now()}`,
    title: targetDescription,
    description: `Implementation plan for: ${targetDescription}`,
    steps,
    createdAt: Date.now(),
  };
}

// Generate diff summary (Karpathy-style progression)
export function generateDiffSummary(plan: MultiFilePlan): string {
  let summary = `# ${plan.title}\n\n`;
  summary += `${plan.description}\n\n`;

  plan.steps.forEach((step, idx) => {
    summary += `## Step ${idx + 1}: ${step.description}\n\n`;

    step.files.forEach(file => {
      const added = file.changes.filter(c => c.type === 'CREATE').length;
      const removed = file.changes.filter(c => c.type === 'REMOVE').length;
      const changed = file.changes.filter(c => c.type === 'CHANGE').length;

      summary += `### ${file.path}\n`;
      summary += `- Added: ${added} lines\n`;
      summary += `- Removed: ${removed} lines\n`;
      summary += `- Changed: ${changed} lines\n\n`;
    });
  });

  return summary;
}

// Apply plan to files (simulation)
export function simulatePlan(plan: MultiFilePlan): Record<string, string> {
  const result: Record<string, string> = {};

  // Start with empty or base files
  plan.steps.forEach(step => {
    step.files.forEach(file => {
      result[file.path] = file.newContent;
    });
  });

  return result;
}

// Compare two versions of a file (microdiff wrapper)
export function compareFiles(oldContent: string, newContent: string): DiffResult[] {
  return diff(oldContent.split('\n'), newContent.split('\n'));
}

// Format diff for display (Karpathy-style)
export function formatDiff(changes: DiffResult[]): string {
  let result = '';

  changes.forEach(change => {
    const path = change.path.join('.');
    switch (change.type) {
      case 'CREATE':
        result += `+ ${path}: ${JSON.stringify(change.value)}\n`;
        break;
      case 'REMOVE':
        result += `- ${path}: ${JSON.stringify(change.value)}\n`;
        break;
      case 'CHANGE':
        result += `~ ${path}: ${JSON.stringify(change.oldValue)} → ${JSON.stringify(change.value)}\n`;
        break;
    }
  });

  return result;
}
